server:
  port: 3000

spring:
  autoconfigure:
    exclude:
      - "org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration"
      - "org.springframework.boot.autoconfigure.data.mongo.MongoRepositoriesAutoConfiguration"

